### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by GoldElysium** [HL-Resistance/hlresistance-preview.github.io#17]
I see that the code is now in React, do you guys want me to create an action and deploy it to fly.io so that we see the actual site when going to the domain?
I already have an express server in HL-Resistance/backend#1, so I could integrate it into that server. There is already a [snippet](https://create-react-app.dev/docs/deployment/#other-solutions) available.

@Ekwok95 @Aeoraa

**Comment by Aeoraa** [comment]
Yes, would be glad if you can do that. I attempted in fixing build settings in PR #18 , build folder so should visible once it's approved and merged.
